#!/usr/bin/env python3
"""
bundle_mod.py — assemble the loadable Tabletop Simulator mod for THE STILL HOUR.

A TTS object exposes a single `LuaScript` string, so the six StillHour modules
are inlined behind a local `require` (a hand-rolled luabundle) and the control
script is appended as the entry code. The result is attached to a control token
and shipped alongside the 30-card player-card bag as one loadable save.

Outputs:
  dist/stillhour_bundle.lua    the combined LuaScript (for inspection/debug)
  dist/the_still_hour_mod.json  a TTS save: card bag + scripted control token

Run: python3 pipeline/bundle_mod.py   (from repo root)
"""
import hashlib
import json
import os

MODULES = [
    "Constants",
    "CampaignState",
    "Dissonance",
    "LoopFlags",
    "Hourglass",
    "Aging",
]

PREAMBLE = """-- ============================================================================
-- THE STILL HOUR — generated bundle. DO NOT EDIT BY HAND.
-- Source: src/StillHour/*.ttslua + src/tts/control.lua ; assembled by
-- pipeline/bundle_mod.py. Edit the source and rebuild.
-- ============================================================================
local __modules = {}
local __loaded = {}
local function require(name)
  local cached = __loaded[name]
  if cached ~= nil then return cached end
  local factory = __modules[name]
  if factory == nil then
    error("StillHour bundle: module not found: " .. tostring(name))
  end
  local result = factory()
  if result == nil then result = true end
  __loaded[name] = result
  return result
end
"""


def guid(seed):
    return hashlib.sha1(seed.encode("utf-8")).hexdigest()[:6]


def transform(x):
    return {"posX": x, "posY": 1.2, "posZ": 0, "rotX": 0, "rotY": 180, "rotZ": 0,
            "scaleX": 1, "scaleY": 1, "scaleZ": 1}


def build_bundle(root):
    parts = [PREAMBLE]
    for name in MODULES:
        path = os.path.join(root, "src", "StillHour", name + ".ttslua")
        body = open(path, encoding="utf-8").read()
        parts.append('__modules["StillHour/%s"] = function()\n%s\nend\n' % (name, body))
    control = open(os.path.join(root, "src", "tts", "control.lua"), encoding="utf-8").read()
    parts.append("-- ===== control entry script =====\n" + control)
    return "\n".join(parts)


def build_save(root, bundle):
    # The player-card bag (generated by build_cards.py).
    deck_path = os.path.join(root, "dist", "the_still_hour.json")
    card_bag = json.load(open(deck_path))["ObjectStates"][0]
    card_bag["Transform"] = transform(-3)

    control = {
        "Name": "BlockSquare",
        "Transform": transform(3),
        "Nickname": "THE STILL HOUR — Control",
        "Description": "Click 'Run Tests'. Open the console with the ` key to read output.",
        "GUID": guid("sthr-control"),
        "ColorDiffuse": {"r": 0.13, "g": 0.11, "b": 0.18},
        "Locked": True,
        "Tags": ["StillHour"],
        "LuaScript": bundle,
        "LuaScriptState": "",
    }

    return {
        "SaveName": "THE STILL HOUR",
        "GameMode": "THE STILL HOUR",
        "GameType": "",
        "GameComplexity": "",
        "Tags": ["StillHour"],
        "Gravity": 0.5,
        "PlayArea": 0.5,
        "Date": "",
        "Table": "Table_Custom",
        "Sky": "Sky_Museum",
        "Note": "THE STILL HOUR — vertical slice. Card bag + scripted control "
                "token (state manager, Dissonance/[static], Hourglass, Aging, "
                "loop flags) with an in-engine test harness. See docs/INTEGRATION.md.",
        "Rules": "",
        "TabStates": {},
        "VersionNumber": "",
        "ObjectStates": [card_bag, control],
    }


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    os.makedirs(os.path.join(root, "dist"), exist_ok=True)

    bundle = build_bundle(root)
    bundle_path = os.path.join(root, "dist", "stillhour_bundle.lua")
    with open(bundle_path, "w", encoding="utf-8") as f:
        f.write(bundle)

    save = build_save(root, bundle)
    save_path = os.path.join(root, "dist", "the_still_hour_mod.json")
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(save, f, indent=2, ensure_ascii=False)

    # Validate the save round-trips and the control script embedded cleanly.
    reloaded = json.load(open(save_path, encoding="utf-8"))
    objs = reloaded["ObjectStates"]
    assert len(objs) == 2, "expected card bag + control object"
    ctrl = next(o for o in objs if o.get("Nickname", "").endswith("Control"))
    assert "runStillHourTests" in ctrl["LuaScript"], "control script missing harness"
    cards = next(o for o in objs if o.get("ContainedObjects"))
    print("OK  bundle:   %s  (%d bytes Lua)" % (bundle_path, len(bundle)))
    print("OK  save:     %s" % save_path)
    print("OK  contents: %d-card bag + '%s'" % (len(cards["ContainedObjects"]), ctrl["Nickname"]))


if __name__ == "__main__":
    main()
