#!/usr/bin/env python3
"""
bundle_mod.py — assemble the loadable Tabletop Simulator mod for THE STILL HOUR.

A TTS object exposes a single `LuaScript` string, so the six StillHour modules
are inlined behind a local `require` (a hand-rolled luabundle) and the control
script is appended as the entry code. The result is attached to a control token
and shipped alongside the 30-card player-card bag as one loadable save.

Outputs:
  dist/stillhour_bundle.lua    the combined LuaScript (for inspection/debug)
  dist/the_still_hour_mod.json  a TTS save: card bag + scripted control token

Run: python3 pipeline/bundle_mod.py   (from repo root)
"""
import hashlib
import json
import os

MODULES = [
    "Constants",
    "CampaignState",
    "Dissonance",
    "LoopFlags",
    "Hourglass",
    "Aging",
    "Appointed",
    "Knowledge",
    "Locations",
    "Interlude",
    "SCED",
    "ChaosBag",
    "Board",
]

# The [static] chaos token image: the hosted URL publish_hosted.py writes to
# pipeline/art_urls.json ("_static_token"), else a neutral placeholder.
STATIC_TOKEN_PLACEHOLDER = "__STILLHOUR_STATIC_TOKEN_URL__"
STATIC_TOKEN_FALLBACK = "https://placehold.co/512x512/14121e/e2ecf0.png?text=static"


def static_token_url(root):
    path = os.path.join(root, "pipeline", "art_urls.json")
    if os.path.exists(path):
        v = json.load(open(path, encoding="utf-8")).get("_static_token")
        if isinstance(v, dict):
            v = v.get("face")
        if v:
            return v
    return STATIC_TOKEN_FALLBACK

PREAMBLE = """-- ============================================================================
-- THE STILL HOUR — generated bundle. DO NOT EDIT BY HAND.
-- Source: src/StillHour/*.ttslua + src/tts/control.lua ; assembled by
-- pipeline/bundle_mod.py. Edit the source and rebuild.
-- ============================================================================
local __modules = {}
local __loaded = {}
local function require(name)
  local cached = __loaded[name]
  if cached ~= nil then return cached end
  local factory = __modules[name]
  if factory == nil then
    error("StillHour bundle: module not found: " .. tostring(name))
  end
  local result = factory()
  if result == nil then result = true end
  __loaded[name] = result
  return result
end
"""


def guid(seed):
    return hashlib.sha1(seed.encode("utf-8")).hexdigest()[:6]


# SCED's table surface sits at y ~1.48: anything spawned lower starts inside
# the table and falls through it. Objects drop in from above, in the open strip
# between the scenario mat (x -6..3) and the row of scenario boxes (x 12.25),
# one after another across the table (z).
SPAWN_X, SPAWN_Y = 24.0, 2.5     # the open area inside SCED's grey lines


def transform(z):
    return {"posX": SPAWN_X, "posY": SPAWN_Y, "posZ": z, "rotX": 0, "rotY": 270, "rotZ": 0,
            "scaleX": 1, "scaleY": 1, "scaleZ": 1}


def build_bundle(root):
    parts = [PREAMBLE]
    token_url = static_token_url(root)
    for name in MODULES:
        path = os.path.join(root, "src", "StillHour", name + ".ttslua")
        body = open(path, encoding="utf-8").read().replace(STATIC_TOKEN_PLACEHOLDER, token_url)
        parts.append('__modules["StillHour/%s"] = function()\n%s\nend\n' % (name, body))
    control = open(os.path.join(root, "src", "tts", "control.lua"), encoding="utf-8").read()
    parts.append("-- ===== control entry script =====\n" + control)
    return "\n".join(parts)


def build_save(root, bundle):
    # The player-card bag (generated by build_cards.py).
    deck_path = os.path.join(root, "dist", "the_still_hour.json")
    card_bag = json.load(open(deck_path, encoding="utf-8"))["ObjectStates"][0]
    card_bag["Transform"] = transform(-3)

    # The encounter bag (The Appointed set), if generated.
    enc_path = os.path.join(root, "dist", "the_still_hour_encounter.json")
    encounter_bag = None
    if os.path.exists(enc_path):
        encounter_bag = json.load(open(enc_path, encoding="utf-8"))["ObjectStates"][0]
        encounter_bag["Transform"] = transform(-6)

    control = {
        "Name": "BlockSquare",
        "Transform": transform(3),
        "Nickname": "THE STILL HOUR — Control",
        "Description": "Click 'Run Tests'. Open the console with the ` key to read output.",
        "GUID": guid("sthr-control"),
        "ColorDiffuse": {"r": 0.13, "g": 0.11, "b": 0.18},
        "Locked": True,
        "Tags": ["StillHour"],
        "LuaScript": bundle,
        "LuaScriptState": "",
    }

    # One physical [static] chaos token (same data the control script spawns
    # into the chaos bag; mirrors SCED Global.spawnChaosToken's token shape).
    static_token = {
        "Name": "Custom_Tile",
        "Transform": dict(transform(6), scaleX=0.81, scaleY=1, scaleZ=0.81),
        "Nickname": "Static",
        "Description": "[static] chaos token (-3). When revealed, raise Dissonance by 1.",
        "GUID": guid("sthr-static-token"),
        "ColorDiffuse": {"r": 1, "g": 1, "b": 1},
        "Tags": ["StillHourStatic"],
        "Hands": False,
        "HideWhenFaceDown": False,
        "CustomImage": {
            "ImageURL": static_token_url(root), "ImageSecondaryURL": "",
            "ImageScalar": 1.0, "WidthScale": 0.0,
            "CustomTile": {"Type": 2, "Thickness": 0.1, "Stretch": True, "Stackable": False},
        },
        "LuaScript": "",
        "LuaScriptState": "",
    }

    return {
        "SaveName": "THE STILL HOUR",
        "GameMode": "THE STILL HOUR",
        "GameType": "",
        "GameComplexity": "",
        "Tags": ["StillHour"],
        "Gravity": 0.5,
        "PlayArea": 0.5,
        "Date": "",
        "Table": "Table_Custom",
        "Sky": "Sky_Museum",
        "Note": "THE STILL HOUR — vertical slice. Card bag + scripted control "
                "token (state manager, Dissonance/[static], Hourglass, Aging, "
                "loop flags) with an in-engine test harness. See docs/INTEGRATION.md.",
        "Rules": "",
        "TabStates": {},
        "VersionNumber": "",
        "ObjectStates": [o for o in (card_bag, encounter_bag, control, static_token)
                         if o is not None],
    }


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    os.makedirs(os.path.join(root, "dist"), exist_ok=True)

    bundle = build_bundle(root)
    bundle_path = os.path.join(root, "dist", "stillhour_bundle.lua")
    with open(bundle_path, "w", encoding="utf-8") as f:
        f.write(bundle)

    save = build_save(root, bundle)
    save_path = os.path.join(root, "dist", "the_still_hour_mod.json")
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(save, f, indent=2, ensure_ascii=False)

    # Validate the save round-trips and the control script embedded cleanly.
    reloaded = json.load(open(save_path, encoding="utf-8"))
    objs = reloaded["ObjectStates"]
    ctrl = next(o for o in objs if o.get("Nickname", "").endswith("Control"))
    assert "runStillHourTests" in ctrl["LuaScript"], "control script missing harness"
    assert STATIC_TOKEN_PLACEHOLDER not in ctrl["LuaScript"], "static token URL not substituted"
    bags = [o for o in objs if o.get("ContainedObjects")]
    total_cards = sum(len(b["ContainedObjects"]) for b in bags)
    print("OK  bundle:   %s  (%d bytes Lua)" % (bundle_path, len(bundle)))
    print("OK  save:     %s" % save_path)
    print("OK  contents: %d objects, %d cards across %d bag(s) + '%s'"
          % (len(objs), total_cards, len(bags), ctrl["Nickname"]))


if __name__ == "__main__":
    main()
