#!/usr/bin/env python3
"""
bundle_mod.py — assemble the loadable Tabletop Simulator mod for THE STILL HOUR.

A TTS object exposes a single `LuaScript` string, so the six StillHour modules
are inlined behind a local `require` (a hand-rolled luabundle) and the control
script is appended as the entry code. The result is attached to a control token
and shipped alongside the 30-card player-card bag as one loadable save.

Outputs:
  dist/stillhour_bundle.lua    the combined LuaScript (for inspection/debug)
  dist/the_still_hour_mod.json  a TTS save: card bag + scripted control token

Run: python3 pipeline/bundle_mod.py   (from repo root)
The release build runs this through pipeline/publish_hosted.py; writing
placeholder or file:/// image URLs into dist/ is refused unless --local.
"""
import argparse
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_cards import add_local_flag, release_guard  # noqa: E402
from campaign_config import CFG  # noqa: E402

# the campaign's Lua rules modules (src/<lua_dir>/<name>.ttslua), bundled in order
MODULES = list(CFG.lua_modules)
TOKEN = CFG.static_token or {}

# The [static] chaos token image: the hosted URL publish_hosted.py writes to
# pipeline/art_urls.json ("_static_token"), else a neutral placeholder.
STATIC_TOKEN_PLACEHOLDER = TOKEN.get("placeholder", "__STATIC_TOKEN_URL__")
STATIC_TOKEN_FALLBACK = TOKEN.get("fallback_url", "https://placehold.co/512x512/14121e/e2ecf0.png?text=static")


# The guide's page index (src/<lua_dir>/Guide.ttslua): "key=page,..." from the page numbers the guide
# PDF build wrote next to the PDF (pipeline/build_guide_pdf.py), through the campaign's
# "guide_page_keys" (section title -> key). Empty when there is no such file.
GUIDE_PAGES_PLACEHOLDER = "__STILLHOUR_GUIDE_PAGES__"


def guide_pages_text(root):
    keys = CFG.get("guide_page_keys") or {}
    path = os.path.join(root, "dist", "guide", CFG.slug + "_campaign_guide_pages.json")
    if not keys or not os.path.exists(path):
        return ""
    pages = json.load(open(path, encoding="utf-8")).get("pages", {})
    return ",".join("%s=%d" % (keys[t], pages[t]) for t in sorted(keys, key=lambda t: pages.get(t, 0))
                    if t in pages)


def static_token_url(root):
    path = CFG.path("art_urls")
    if os.path.exists(path):
        v = json.load(open(path, encoding="utf-8")).get("_static_token")
        if isinstance(v, dict):
            v = v.get("face")
        if v:
            return v
    return STATIC_TOKEN_FALLBACK

PREAMBLE = """-- ============================================================================
-- %(upper)s — generated bundle. DO NOT EDIT BY HAND.
-- Source: src/%(dir)s/*.ttslua + %(control)s ; assembled by
-- pipeline/bundle_mod.py. Edit the source and rebuild.
-- ============================================================================
local __modules = {}
local __loaded = {}
local function require(name)
  local cached = __loaded[name]
  if cached ~= nil then return cached end
  local factory = __modules[name]
  if factory == nil then
    error("%(dir)s bundle: module not found: " .. tostring(name))
  end
  local result = factory()
  if result == nil then result = true end
  __loaded[name] = result
  return result
end
""" % {"upper": CFG.upper_name, "dir": CFG.lua_dir, "control": CFG.control_lua}


def guid(seed):
    return hashlib.sha1(seed.encode("utf-8")).hexdigest()[:6]


# SCED's table surface sits at y ~1.48: anything spawned lower starts inside
# the table and falls through it. Objects drop in from above, in the open strip
# between the scenario mat (x -6..3) and the row of scenario boxes (x 12.25),
# one after another across the table (z).
SPAWN_X, SPAWN_Y = 24.0, 2.5     # the open area inside SCED's grey lines


def transform(z):
    return {"posX": SPAWN_X, "posY": SPAWN_Y, "posZ": z, "rotX": 0, "rotY": 270, "rotZ": 0,
            "scaleX": 1, "scaleY": 1, "scaleZ": 1}


def build_bundle(root):
    parts = [PREAMBLE]
    token_url = static_token_url(root)
    guide_pages = guide_pages_text(root)
    for name in MODULES:
        path = os.path.join(root, "src", CFG.lua_dir, name + ".ttslua")
        body = (open(path, encoding="utf-8").read().replace(STATIC_TOKEN_PLACEHOLDER, token_url)
                .replace(GUIDE_PAGES_PLACEHOLDER, guide_pages))
        parts.append('__modules["%s/%s"] = function()\n%s\nend\n' % (CFG.lua_dir, name, body))
    control = open(os.path.join(root, CFG.control_lua), encoding="utf-8").read()
    parts.append("-- ===== control entry script =====\n" + control)
    return "\n".join(parts)


def build_save(root, bundle):
    # The player-card bag (generated by build_cards.py).
    deck_path = os.path.join(root, "dist", CFG.slug + ".json")
    card_bag = json.load(open(deck_path, encoding="utf-8"))["ObjectStates"][0]
    card_bag["Transform"] = transform(-3)

    # The encounter bag (The Appointed set), if generated.
    enc_path = os.path.join(root, "dist", CFG.slug + "_encounter.json")
    encounter_bag = None
    if os.path.exists(enc_path):
        encounter_bag = json.load(open(enc_path, encoding="utf-8"))["ObjectStates"][0]
        encounter_bag["Transform"] = transform(-6)

    control = {
        "Name": "BlockSquare",
        "Transform": transform(3),
        "Nickname": CFG.upper_name + " — Control",
        "Description": CFG.name + ": campaign bookkeeping. See the guide.",
        "GUID": guid(CFG.control_guid),
        "ColorDiffuse": {"r": 0.13, "g": 0.11, "b": 0.18},
        "Locked": True,
        # SCED's Clean Up Helper ("Reset play areas") trashes whatever lies in the play area that is not locked
        # and not tagged like this, as it does with the official campaign guide and log
        "Tags": [CFG.tag, "CleanUpHelper_ignore"],
        "LuaScript": bundle,
        "LuaScriptState": "",
    }

    # One physical [static] chaos token (same data the control script spawns
    # into the chaos bag; mirrors SCED Global.spawnChaosToken's token shape).
    # (campaign-specific: only a campaign with its own chaos token has one)
    static_token = None if not TOKEN else {
        "Name": "Custom_Tile",
        "Transform": dict(transform(6), scaleX=0.81, scaleY=1, scaleZ=0.81),
        "Nickname": TOKEN["nickname"],
        "Description": TOKEN["description"],
        "GUID": guid(TOKEN["id"]),
        "ColorDiffuse": {"r": 1, "g": 1, "b": 1},
        "Tags": [TOKEN["tag"], "CleanUpHelper_ignore"],
        "Hands": False,
        "HideWhenFaceDown": False,
        "CustomImage": {
            "ImageURL": static_token_url(root), "ImageSecondaryURL": "",
            "ImageScalar": 1.0, "WidthScale": 0.0,
            "CustomTile": {"Type": 2, "Thickness": 0.1, "Stretch": True, "Stackable": False},
        },
        "LuaScript": "",
        "LuaScriptState": "",
    }

    return {
        "SaveName": CFG.upper_name,
        "GameMode": CFG.upper_name,
        "GameType": "",
        "GameComplexity": "",
        "Tags": [CFG.tag],
        "Gravity": 0.5,
        "PlayArea": 0.5,
        "Date": "",
        "Table": "Table_Custom",
        "Sky": "Sky_Museum",
        "Note": CFG.get("mod_note", CFG.upper_name + " — card bags and the scripted Control token."),
        "Rules": "",
        "TabStates": {},
        "VersionNumber": "",
        "ObjectStates": [o for o in (card_bag, encounter_bag, control, static_token)
                         if o is not None],
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description="Assemble the TTS mod for " + CFG.upper_name + ".")
    ap.add_argument("--campaign", help="campaign id (campaigns/<id>/build.json); default $CAMPAIGN or still_hour")
    add_local_flag(ap)
    args = ap.parse_args(argv)
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    os.makedirs(os.path.join(root, "dist"), exist_ok=True)

    bundle = build_bundle(root)
    bundle_path = os.path.join(root, "dist", CFG.bundle_out)
    save = build_save(root, bundle)
    save_path = os.path.join(root, "dist", CFG.slug + "_mod.json")
    save_text = json.dumps(save, indent=2, ensure_ascii=False)
    # check both before writing either, so a refusal leaves dist/ untouched
    release_guard(bundle_path, bundle, args.local)
    release_guard(save_path, save_text, args.local)
    with open(bundle_path, "w", encoding="utf-8") as f:
        f.write(bundle)
    with open(save_path, "w", encoding="utf-8") as f:
        f.write(save_text)

    # Validate the save round-trips and the control script embedded cleanly.
    reloaded = json.load(open(save_path, encoding="utf-8"))
    objs = reloaded["ObjectStates"]
    ctrl = next(o for o in objs if o.get("Nickname", "").endswith("Control"))
    assert CFG.tests_entry in ctrl["LuaScript"], "control script missing harness"
    assert STATIC_TOKEN_PLACEHOLDER not in ctrl["LuaScript"], "static token URL not substituted"
    bags = [o for o in objs if o.get("ContainedObjects")]
    total_cards = sum(len(b["ContainedObjects"]) for b in bags)
    print("OK  bundle:   %s  (%d bytes Lua)" % (bundle_path, len(bundle)))
    print("OK  save:     %s" % save_path)
    print("OK  contents: %d objects, %d cards across %d bag(s) + '%s'"
          % (len(objs), total_cards, len(bags), ctrl["Nickname"]))


if __name__ == "__main__":
    main()
